services:
  postgresql:
    image: "postgres:15.3"
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  microuser:
    build: ./microUser
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  microtrip:
    build: ./microTrip
    ports:
      - "8001:8001"
    depends_on:
      - postgresql

  micropayment:
    build: ./microPayment
    ports:
      - "8002:8002"
    depends_on:
      - postgresql

  microdispatch:
    build: ./microDispatch
    ports:
      - "8003:8003"
    depends_on:
      - postgresql

  micronotification:
    build: ./microNotification
    ports:
      - "8004:8004"