services:
  postgres:
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: microtrip_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microtrip
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microtrip_user -d microtrip"]
      interval: 10s
      retries: 5
      timeout: 5s
  microtrip:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres