services:
  postgres:
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: microuser_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microuser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microuser_user -d microuser"]
      interval: 10s
      retries: 5
      timeout: 5s


  microuser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy 
    