services:
  postgres:
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: micropayment_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micropayment
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U micropayment_user -d micropayment"]
      interval: 10s
      retries: 5
      timeout: 5s

  micropayment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres